# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/14158/Assignment5/Assignment5.cache/wt [current_project]
set_property parent.project_path C:/Users/14158/Assignment5/Assignment5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/14158/Assignment5/Assignment5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  {C:/Users/14158/Desktop/CMPE 140/memfile.dat}
  {C:/Users/14158/Desktop/CMPE 140/lab8.dat}
}
read_verilog -library xil_defaultlib {
  C:/Users/14158/Assignment5/Assignment5.srcs/sources_1/new/SoC_reg.v
  C:/Users/14158/Assignment5/Assignment5.srcs/sources_1/new/SoC_top.v
  C:/Users/14158/Assignment5/Assignment5.srcs/sources_1/new/ad.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/datapath/adder.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/datapath/alu.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/control_unit/auxdec.v
  C:/Users/14158/Desktop/basys3_single_cycle_mips_validation/button_debouncer.v
  C:/Users/14158/Desktop/factorial/check_error.v
  C:/Users/14158/Desktop/basys3_single_cycle_mips_validation/clk_gen.v
  C:/Users/14158/Desktop/factorial/cmp.v
  C:/Users/14158/Desktop/factorial/cnt.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/control_unit/controlunit.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/datapath/datapath.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/memory/dmem.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/datapath/dreg.v
  C:/Users/14158/Assignment5/Assignment5.srcs/sources_1/new/fact_ad.v
  C:/Users/14158/Desktop/factorial/fact_cu.v
  C:/Users/14158/Desktop/factorial/fact_datapath.v
  C:/Users/14158/Assignment5/Assignment5.srcs/sources_1/new/fact_top.v
  C:/Users/14158/Desktop/factorial/factorial.v
  C:/Users/14158/Assignment5/Assignment5.srcs/sources_1/new/gpio_ad.v
  C:/Users/14158/Assignment5/Assignment5.srcs/sources_1/new/gpio_top.v
  C:/Users/14158/Desktop/basys3_single_cycle_mips_validation/hex_to_7seg.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/memory/imem.v
  C:/Users/14158/Desktop/basys3_single_cycle_mips_validation/led_mux.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/control_unit/maindec.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/mips/mips.v
  C:/Users/14158/Desktop/factorial/mul.v
  C:/Users/14158/Assignment5/Assignment5.srcs/sources_1/new/multiply.v
  C:/Users/14158/Desktop/factorial/mux1to2.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/datapath/mux2.v
  C:/Users/14158/Desktop/factorial/mux2to1.v
  C:/Users/14158/Assignment5/Assignment5.srcs/sources_1/new/mux4to1.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/datapath/regfile.v
  C:/Users/14158/Desktop/factorial/register.v
  C:/Users/14158/Desktop/lab5_processor_design_1/single_cycle_mips_source_initial/datapath/signext.v
  C:/Users/14158/Assignment5/Assignment5.srcs/sources_1/new/FPGA_top_level.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/14158/Desktop/basys3_single_cycle_mips_validation/mips_fpga.xdc
set_property used_in_implementation false [get_files C:/Users/14158/Desktop/basys3_single_cycle_mips_validation/mips_fpga.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FPGA_top_level -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FPGA_top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FPGA_top_level_utilization_synth.rpt -pb FPGA_top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
